config/routes.rb
Rails.application.routes.draw do
  resources :urls
  get "s/index"
  get "s/list"


  root "urls#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
class Url < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/s_controller.rb
class SController < ApplicationController
  def index
  end

  def list
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: %i[ show edit update destroy ]

  # GET /urls or /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1 or /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls or /urls.json
  def create
    base_url = "http://armijo.au"
    next_id = Url.maximum(:id).next
    short_url = ShortUrlGenerator.generate(base_url, next_id)

    new_params = new_url_params
    new_params["short_url"] = short_url

    @url = Url.new(new_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: "Url was successfully created." }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1 or /urls/1.json
  def update
    respond_to do |format|
      if @url.update(update_url_params)
        format.html { redirect_to @url, notice: "Url was successfully updated." }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1 or /urls/1.json
  def destroy
    @url.destroy!

    respond_to do |format|
      format.html { redirect_to urls_path, status: :see_other, notice: "Url was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    def new_url_params
      params.require(:url).permit(:long_url, :description, :owner)
    end

    # Only allow a list of trusted parameters through.
    def update_url_params
      params.require(:url).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/s_helper.rb
module SHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title><%= content_for(:title) || "Url Shortener" %></title>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 's/header' %>
    <div class="container">
      <br />
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/s/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'URL Shortener', s_index_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Create', s_index_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to 'List', s_list_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to 'Shorten URL', new_url_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to 'View shortened URLs', urls_path, class:"nav-link"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/s/index.html.erb
<p>Enter the long URL to shorten:</p>

app/views/s/list.html.erb
<p>These are all the url's that have been shortened:</p>

app/views/urls/_url.html.erb
<div id="<%= dom_id url %>">
  <p>
    <strong>Long url:</strong>
    <%= url.long_url %>
  </p>

  <p>
    <strong>Short url:</strong>
    <%= url.short_url %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= url.description %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= url.owner %>
  </p>

</div>

app/views/urls/edit.html.erb
<% content_for :title, "Editing url" %>

<h1>Editing url</h1>

<br />
<%= form_with(model: @url) do |form| %>
  <% if @url.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% @url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :long_url, style: "display: block" %>
    <%= form.text_field :long_url, class: "form-control", placeholder: "http://www.example.com/this-is-a-long-url", disabled: true %>
  </div>

  <div class="field form-group">
    <%= form.label :short_url, style: "display: block" %>
    <%= form.text_field :short_url, class: "form-control", placeholder: "http://short.url/1", disabled: true %>
  </div>

  <div class="field form-group">
    <%= form.label "#{:description} (optional)", style: "display: block" %>
    <%= form.text_field :description, class: "form-control", placeholder: "Description" %>
  </div>

  <div class="field form-group">
    <%= form.label :owner, style: "display: block" %>
    <%= form.text_field :owner, class: "form-control", placeholder: "someone@domain.com", disabled: true %>
  </div>

  <br />

  <div class="actions">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/urls/index.html.erb
<% content_for :title, "Urls" %>

<h1>Shortened Urls</h1>

<% if (@urls.length == 0) %>
  <p>No items to display.</p>
<% else %>
  <table class="table table-striped table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Long url</th>
        <th scope="col">Short url</th>
        <th scope="col">Description</th>
        <th scope="col">Owner</th>
        <th scope="col">View</th>
      </tr>
    </thead>
    <tbody>
      <% @urls.each do |url| %>
      <tr>
        <td><a href="<%= url.long_url %>"><%= url.long_url %></a></td>
        <td><a href="<%= url.short_url %>"><%= url.short_url %></a></td>
        <td><%= url.description %></td>
        <td><%= url.owner %></td>
        <td><%= link_to "View", url %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to "Shorten a new URL", new_url_path, class: "btn btn-secondary" %>

app/views/urls/new.html.erb
<% content_for :title, "Shorten URL" %>

<h1>Shorten URL</h1>

<br />
<%= form_with(model: @url) do |form| %>
  <% if @url.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% @url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :long_url, style: "display: block" %>
    <%= form.text_field :long_url, class: "form-control", placeholder: "http://www.example.com/this-is-a-long-url" %>
  </div>

  <div class="field form-group">
    <%= form.label "#{:description} (optional)", style: "display: block" %>
    <%= form.text_field :description, class: "form-control", placeholder: "Description" %>
  </div>

  <div class="field form-group">
    <%= form.label "#{:owner} (optional)", style: "display: block" %>
    <%= form.text_field :owner, class: "form-control", placeholder: "someone@domain.com" %>
  </div>

  <br />

  <div class="actions">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/urls/show.html.erb
<div class="jumbotron">
  <h1 class="display-5"><%= @url.description %></h1>

  <p>Long URL: <a href="<%= @url.long_url %>"><%= @url.long_url %></a></p>
  <p>Short URL: <a href="<%= @url.short_url %>"><%= @url.short_url %></a></p>
  <p>Owner: <%= @url.owner %></p>

  <div>
    <%= link_to "Edit this url", edit_url_path(@url), class: "btn btn-secondary" %>
    <%= link_to "Back to urls", urls_path, class: "btn btn-dark" %>
    <!--<%= link_to "Destroy this url", @url, method: :delete, class: "btn btn-secondary" %>-->
  </div>
</div>